frase = ('Curso em Video Python')
print(frase[6])
print(frase[:5])
print(frase[9:14])
print(frase[9::3])
tam = len(frase)
print(tam)
qtd = frase.count('o')
frase.count('o', 0, 13)
print(qtd)
pos = frase.find('deo')
print(pos)
teste = 'Curso' in frase
print(teste)
frase2 = frase.replace('Python', 'Android')
print(frase2)
frase3 = frase.upper()
print(frase3)
frase4 = frase.lower()
print(frase4)
frase5 = frase.capitalize()
print(frase5)
frase6 = frase.title()
print(frase6)
frasenova = ('   Aprendendo Python  ')
frasenova = frasenova.strip()
#frasenova = frasenova.rstrip()
#frasenova = frasenova.lstrip()
print(frasenova)
fraseseparada = frase.split()
print(fraseseparada)
frasejunta = '-'.join(frase)
print(frasejunta)